### ISSUE TITLE
Crash on incomplete slider object

### ISSUE THREAD

**Issue by CosminPerRam** [HaselLoyance/osu-parser#1]
While trying to parse the map `155118 Drop - Granat`, the `extra` difficulty, the program crashes because of an incomplete slider object:

`208,144,18185,6,0,L|290:179,1,89.9999952316285,4|0,0:0|0:0,0:0:0:0:` <-this is a normal slider object, just above the other one
`456,200,18517,2,0,L|373:164,1,89.9999952316285`

The parser crashes on `OsuParser.cpp` at line 555, with the error `vector subscript out of range` because there is no 8th arg on this object, i tried to state the problem on the forum and ask for an explanation [here](https://osu.ppy.sh/community/forums/topics/1233173) but no luck yet, I will modify it to check if it the size is bigger than 7, and if not, fill the objects with empty ones `0|0,0:0|0:0`, but I feel like this is not a good approach for this problem.

**Comment by yar-sh** [comment]
Yooo that's neat. Never thought this library is going to be used!
Can you make a PR with this fix so I can merge it in?

**Comment by CosminPerRam** [comment]
I found out more problems, I'll figure out a fix for them, thanks for responding!

**Comment by CosminPerRam** [comment]
#

**Comment by CosminPerRam** [comment]
#2

**Comment by yar-sh** [comment]
Closed in #2
